// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Movie", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("language");

                    b.Property<int>("length");

                    b.Property<string>("name");

                    b.Property<double>("price");

                    b.Property<DateTime>("startTime");

                    b.HasKey("id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("API.Models.MovieSeat", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Movieid");

                    b.Property<bool>("reserved");

                    b.Property<int>("row");

                    b.Property<int>("seatNumber");

                    b.Property<long?>("userId");

                    b.HasKey("id");

                    b.HasIndex("Movieid");

                    b.HasIndex("userId");

                    b.ToTable("MovieSeats");
                });

            modelBuilder.Entity("API.Models.ParkingReservation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("place");

                    b.Property<string>("plate");

                    b.HasKey("id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.Property<string>("phoneNumber");

                    b.Property<string>("role");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.MovieSeat", b =>
                {
                    b.HasOne("API.Models.Movie", "Movie")
                        .WithMany("seats")
                        .HasForeignKey("Movieid");

                    b.HasOne("API.Models.User", "user")
                        .WithMany("MovieSeats")
                        .HasForeignKey("userId");
                });
#pragma warning restore 612, 618
        }
    }
}
